### ISSUE TITLE
Browser does not show results in the same order as returned by the API

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk-browser#53]
To reproduce

1. Go to https://kgtk.isi.edu/browser
2. search for q30
3. Results look like
![image](https://user-images.githubusercontent.com/6811931/144339177-b067e960-fe5a-4c60-b00f-ea131413cf7d.png)
4. Notice that Q30 is not the top result
5. Delete Q30 from the search box, the correct results show up
 ![image](https://user-images.githubusercontent.com/6811931/144339267-314ea6a4-a0b8-4c02-b761-b0748658e908.png)
6. Same thing happens for a phrase search, for example: `bara oba` (this case is replicable only in the new API code in the current `dev` branch)
7. Replicable on Chrome, Firefox and Safari

**Comment by g1eb** [comment]
this was a side effect of the `getOptionLabel` function in the Material UI Autocomplete component. This function is used to filter out the results and as it was using node descriptions it was missing the refs containing the Qnode ID.

**Comment by g1eb** [comment]
Apparently you need to override the default filtering to return all options in the autocomplete menu dropdown, regardless of what users type in (the burden of filtering in our case is put on the API); fixed in the `dev` branch, see commit https://github.com/usc-isi-i2/kgtk-browser/commit/0fade063e5edecdd7b4ead5df6dabb64f69fc8f0
